name: Generate demo file

on: push

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Website to file
        uses: PabloLec/website-to-gif@2.1.5
        with:
          url: "https://lexgenius.s3.us-west-2.amazonaws.com/index2.html"
          window_width: 1920
          window_heigh: 1080
          scroll_step: 5
          time_per_frame: 80
      - name: Commit file to GH repo1
        run: |
          git config --global user.name "PabloLec/website-to-gif"
          git config --global user.email "action@github.com"
          git add .
          git commit -m 'Update file'
          git push
