name: Generate demo file

on: push

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Website to file
        uses: PabloLec/website-to-gif@2.1.5
        with:
          url: "https://cdn.lexgenius.ai/20240712/ads/451833997641577.html"
          window-width: 428
          window-height: 926
          scroll_step: 15
          time_per_frame: 80
          
      - name: Commit file to GH repo
        run: |
          git config --global user.name "PabloLec/website-to-gif"
          git config --global user.email "action@github.com"
          git add .
          git commit -m 'Update file'
          git push
